/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class go_graphics_nativegl_NativeAreaWindow */

#ifndef _Included_go_graphics_nativegl_NativeAreaWindow
#define _Included_go_graphics_nativegl_NativeAreaWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     go_graphics_nativegl_NativeAreaWindow
 * Method:    openWindow_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_go_graphics_nativegl_NativeAreaWindow_openWindow_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class go_graphics_nativegl_NativeAreaWindow_OpenGLThread */

#ifndef _Included_go_graphics_nativegl_NativeAreaWindow_OpenGLThread
#define _Included_go_graphics_nativegl_NativeAreaWindow_OpenGLThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
