/*******************************************************************************
 * Copyright (c) 2015
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class go_graphics_nativegl_NativeAreaWindow */

#ifndef _Included_go_graphics_nativegl_NativeAreaWindow
#define _Included_go_graphics_nativegl_NativeAreaWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     go_graphics_nativegl_NativeAreaWindow
 * Method:    openWindow_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_go_graphics_nativegl_NativeAreaWindow_openWindow_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class go_graphics_nativegl_NativeAreaWindow_OpenGLThread */

#ifndef _Included_go_graphics_nativegl_NativeAreaWindow_OpenGLThread
#define _Included_go_graphics_nativegl_NativeAreaWindow_OpenGLThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
