/*******************************************************************************
 * Copyright (c) 2015
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *******************************************************************************/
package jsettlers.graphics.map.controls.original;

import jsettlers.common.images.EImageLinkType;
import jsettlers.common.images.OriginalImageLink;

public class ControlPanelLayoutProperties {
	public enum Resolution {
		HEIGHT480,
		HEIGHT600,
		HEIGHT768
	}

	private static final ControlPanelLayoutProperties height480 = new ControlPanelLayoutProperties(Resolution.HEIGHT480);
	private static final ControlPanelLayoutProperties height600 = new ControlPanelLayoutProperties(Resolution.HEIGHT600);
	private static final ControlPanelLayoutProperties height768 = new ControlPanelLayoutProperties(Resolution.HEIGHT768);

	public final float UI_RATIO;
	public final float UI_CENTER_Y;
	public final float UI_CENTER_X;
	public final float UI_DECORATIONRIGHT;
	public final float UI_MINIMAP_DECORATORRIGHT;

	// relative to top minimap area. This is the whole area including the right half.
	public final float MINIMAP_WIDTH;
	public final float MINIMAP_HEIGHT;
	public final float MINIMAP_BOTTOM_Y;
	public final float MINIMAP_BOTTOMLEFT_X;

	public final float MINIMAP_BUTTON_WIDTH;
	public final float MINIMAP_BUTTON_HEIGHT;

	public final float MINIMAP_BUTTON_ABC_TOP;
	public final float MINIMAP_BUTTON_ABC_LEFT;

	public final float MINIMAP_BUTTON_SCROLL_TOP;
	public final float MINIMAP_BUTTON_SCROLL_LEFT;

	public final float MINIMAP_BUTTON_SETTLERS_TOP;
	public final float MINIMAP_BUTTON_SETTLERS_LEFT;

	public final float MINIMAP_BUTTON_BUILDINGS_TOP;
	public final float MINIMAP_BUTTON_BUILDINGS_LEFT;

	// relative to main content
	public final float UI_TABS1_TOP;
	public final float UI_TABS1_BOTTOM;
	public final float UI_TABS1_SIDEMARGIN;
	public final float UI_TABS1_WIDTH;
	public final float UI_TABS1_SPACING;

	public final float UI_TABS2_TOP;
	public final float UI_TABS2_BOTTOM;
	public final float UI_TABS2_SIDEMARGIN;
	public final float UI_TABS2_WIDTH;
	public final float UI_TABS2_SPACING;

	public final float CONTENT_LEFT;
	public final float CONTENT_BOTTOM;
	public final float CONTENT_RIGHT;
	public final float CONTENT_TOP;

	public final float SYSTEM_BUTTON_TOP;
	public final float SYSTEM_BUTTON_BOTTOM;
	public final float SYSTEM_BUTTON_LEFT;
	public final float SYSTEM_BUTTON_RIGHT;

	public final float LOWER_TABS_TOP;
	public final float LOWER_TABS_BOTTOM;
	public final float LOWER_TABS_LEFT;
	public final float LOWER_TABS_WIDTH;

	public final OriginalImageLink UI_BG_SEQ_MAIN;
	public final OriginalImageLink UI_BG_SEQ_MINIMAPR;
	public final OriginalImageLink UI_BG_SEQ_MINIMAPL;
	public final OriginalImageLink UI_BG_SEQ_RIGHT;

	// Raw Image Dimensions

	// Minimap left-half graphic:
	private final float MINIMAP_LEFT_DECORATION_WIDTH_PX;
	private final float MINIMAP_LEFT_DECORATION_HEIGHT_PX;

	private final float MINIMAP_BUTTON_WIDTH_PX;
	private final float MINIMAP_BUTTON_HEIGHT_PX;

	private final float MINIMAP_BUTTON_ABC_TOP_PX;
	private final float MINIMAP_BUTTON_ABC_LEFT_PX;

	private final float MINIMAP_BUTTON_SCROLL_TOP_PX;
	private final float MINIMAP_BUTTON_SCROLL_LEFT_PX;

	private final float MINIMAP_BUTTON_SETTLERS_TOP_PX;
	private final float MINIMAP_BUTTON_SETTLERS_LEFT_PX;

	private final float MINIMAP_BUTTON_BUILDINGS_TOP_PX;
	private final float MINIMAP_BUTTON_BUILDINGS_LEFT_PX;

	// Main sidebar panel (below minimap):
	private final float PANEL_HEIGHT_PX;
	private final float PANEL_WIDTH_PX;

	private final float PRIMARY_TABS_BUTTON_PLACEHOLDER_WIDTH_PX;
	private final float PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX;
	private final float PRIMARY_TABS_INTER_BUTTON_SPACING_PX;
	private final float PRIMARY_TABS_TOP_PX;
	private final float PRIMARY_TABS_LEFT_PX;

	private final float SECONDARY_TABS_BUTTON_WIDTH_PX;
	private final float SECONDARY_TABS_BUTTON_HEIGHT_PX;
	private final float SECONDARY_TABS_INTER_BUTTON_SPACING_PX;
	private final float SECONDARY_TABS_TOP_PX;
	private final float SECONDARY_TABS_LEFT_PX;

	private final float CONTENT_PANE_WIDTH_PX;
	private final float CONTENT_PANE_HEIGHT_PX;
	private final float CONTENT_PANE_TOP_PX;
	private final float CONTENT_PANE_LEFT_PX;

	private final float SYSTEM_BUTTON_PLACEHOLDER_WIDTH_PX;
	private final float SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX;
	private final float SYSTEM_BUTTON_TOP_PX;
	private final float SYSTEM_BUTTON_LEFT_PX;

	private final float LOWER_TABS_BUTTON_WIDTH_PX;
	private final float LOWER_TABS_BUTTON_HEIGHT_PX;
	private final float LOWER_TABS_TOP_PX;
	private final float LOWER_TABS_LEFT_PX;

	public static ControlPanelLayoutProperties getLayoutPropertiesFor(float pixelHeight)
	{
		if (pixelHeight < 600) {
			return height480;
		}
		else if (pixelHeight < 768) {
			return height600;
		}
		else {
			return height768;
		}
	}

	public ControlPanelLayoutProperties() {
		this(Resolution.HEIGHT480);
	}

	private ControlPanelLayoutProperties(Resolution resolution) {
		UI_RATIO = (float) 480 / 209;
		UI_CENTER_Y = (float) 338 / 480;

		int imageSequenceNumber;

		switch (resolution) {
		case HEIGHT480:
			MINIMAP_LEFT_DECORATION_WIDTH_PX = 136;
			MINIMAP_LEFT_DECORATION_HEIGHT_PX = 142;

			MINIMAP_BUTTON_WIDTH_PX = 18;
			MINIMAP_BUTTON_HEIGHT_PX = 15;
			MINIMAP_BUTTON_ABC_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 5;
			MINIMAP_BUTTON_ABC_LEFT_PX = 5;
			MINIMAP_BUTTON_SCROLL_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 8;
			MINIMAP_BUTTON_SCROLL_LEFT_PX = 35;
			MINIMAP_BUTTON_SETTLERS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 26;
			MINIMAP_BUTTON_SETTLERS_LEFT_PX = 26;
			MINIMAP_BUTTON_BUILDINGS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 45;
			MINIMAP_BUTTON_BUILDINGS_LEFT_PX = 16;

			PANEL_WIDTH_PX = 136;
			PANEL_HEIGHT_PX = 338;

			float PRIMARY_BUTTON_IMAGE_SIZE_PX_SMALL = 33;
			PRIMARY_TABS_BUTTON_PLACEHOLDER_WIDTH_PX = PRIMARY_BUTTON_IMAGE_SIZE_PX_SMALL - 1; // Image needs cropping 1 pixel to fit properly.
			PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX = PRIMARY_BUTTON_IMAGE_SIZE_PX_SMALL - 1; // Image needs cropping 1 pixel to fit properly.
			PRIMARY_TABS_INTER_BUTTON_SPACING_PX = 10;
			PRIMARY_TABS_TOP_PX = PANEL_HEIGHT_PX - 14;
			PRIMARY_TABS_LEFT_PX = 9;

			SECONDARY_TABS_BUTTON_WIDTH_PX = 27;
			SECONDARY_TABS_BUTTON_HEIGHT_PX = 24;
			SECONDARY_TABS_INTER_BUTTON_SPACING_PX = 2;
			SECONDARY_TABS_TOP_PX = PANEL_HEIGHT_PX - 46;
			SECONDARY_TABS_LEFT_PX = 10;

			CONTENT_PANE_WIDTH_PX = 118;
			CONTENT_PANE_HEIGHT_PX = 216;
			CONTENT_PANE_TOP_PX = PANEL_HEIGHT_PX - 77;
			CONTENT_PANE_LEFT_PX = 9;

			SYSTEM_BUTTON_PLACEHOLDER_WIDTH_PX = 18;
			SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX = 27;
			SYSTEM_BUTTON_TOP_PX = 9 + SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX;
			SYSTEM_BUTTON_LEFT_PX = 9;

			LOWER_TABS_BUTTON_WIDTH_PX = 24;
			LOWER_TABS_BUTTON_HEIGHT_PX = 24;
			LOWER_TABS_TOP_PX = 12 + LOWER_TABS_BUTTON_HEIGHT_PX;
			LOWER_TABS_LEFT_PX = 30;

			UI_CENTER_X = (float) 136 / 209;
			UI_DECORATIONRIGHT = (float) 8 / 209 + UI_CENTER_X;
			UI_MINIMAP_DECORATORRIGHT = 1;

			imageSequenceNumber = 0;
			break;
		case HEIGHT600:
			MINIMAP_LEFT_DECORATION_WIDTH_PX = 176;
			MINIMAP_LEFT_DECORATION_HEIGHT_PX = 170;

			MINIMAP_BUTTON_WIDTH_PX = 24;
			MINIMAP_BUTTON_HEIGHT_PX = 20;
			MINIMAP_BUTTON_ABC_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 5;
			MINIMAP_BUTTON_ABC_LEFT_PX = 5;
			MINIMAP_BUTTON_SCROLL_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 9;
			MINIMAP_BUTTON_SCROLL_LEFT_PX = 44;
			MINIMAP_BUTTON_SETTLERS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 32;
			MINIMAP_BUTTON_SETTLERS_LEFT_PX = 32;
			MINIMAP_BUTTON_BUILDINGS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 55;
			MINIMAP_BUTTON_BUILDINGS_LEFT_PX = 22;

			PANEL_WIDTH_PX = 176;
			PANEL_HEIGHT_PX = 430;

			float PRIMARY_BUTTON_IMAGE_SIZE_PX_MEDIUM = 44;
			PRIMARY_TABS_BUTTON_PLACEHOLDER_WIDTH_PX = PRIMARY_BUTTON_IMAGE_SIZE_PX_MEDIUM - 1;
			PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX = PRIMARY_BUTTON_IMAGE_SIZE_PX_MEDIUM;
			PRIMARY_TABS_INTER_BUTTON_SPACING_PX = 13;
			PRIMARY_TABS_TOP_PX = PANEL_HEIGHT_PX - 5;
			PRIMARY_TABS_LEFT_PX = 9;

			SECONDARY_TABS_BUTTON_WIDTH_PX = 36;
			SECONDARY_TABS_BUTTON_HEIGHT_PX = 32;
			SECONDARY_TABS_INTER_BUTTON_SPACING_PX = 4;
			SECONDARY_TABS_TOP_PX = PRIMARY_TABS_TOP_PX - PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX;
			SECONDARY_TABS_LEFT_PX = 9;

			CONTENT_PANE_WIDTH_PX = 157;
			CONTENT_PANE_HEIGHT_PX = 288;
			CONTENT_PANE_TOP_PX = PANEL_HEIGHT_PX - 91;
			CONTENT_PANE_LEFT_PX = 10;

			float SYSTEM_BUTTON_IMAGE_WIDTH_PX_MEDIUM = 24;
			float SYSTEM_BUTTON_IMAGE_HEIGHT_PX_MEDIUM = 36;
			SYSTEM_BUTTON_PLACEHOLDER_WIDTH_PX = SYSTEM_BUTTON_IMAGE_WIDTH_PX_MEDIUM + 2;
			SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX = SYSTEM_BUTTON_IMAGE_HEIGHT_PX_MEDIUM + 3;
			SYSTEM_BUTTON_TOP_PX = 42;
			SYSTEM_BUTTON_LEFT_PX = 8;

			LOWER_TABS_BUTTON_WIDTH_PX = 32;
			LOWER_TABS_BUTTON_HEIGHT_PX = 32;
			LOWER_TABS_TOP_PX = 7 + LOWER_TABS_BUTTON_HEIGHT_PX;
			LOWER_TABS_LEFT_PX = 38;

			UI_CENTER_X = (float) 140 / 209;
			UI_DECORATIONRIGHT = (float) 8 / 209 + UI_CENTER_X;
			UI_MINIMAP_DECORATORRIGHT = 0.98f;

			imageSequenceNumber = 1;
			break;
		default:
		case HEIGHT768:
			MINIMAP_LEFT_DECORATION_WIDTH_PX = 216;
			MINIMAP_LEFT_DECORATION_HEIGHT_PX = 224;

			MINIMAP_BUTTON_WIDTH_PX = 30;
			MINIMAP_BUTTON_HEIGHT_PX = 25;
			MINIMAP_BUTTON_ABC_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 8;
			MINIMAP_BUTTON_ABC_LEFT_PX = 8;
			MINIMAP_BUTTON_SCROLL_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 13;
			MINIMAP_BUTTON_SCROLL_LEFT_PX = 57;
			MINIMAP_BUTTON_SETTLERS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 43;
			MINIMAP_BUTTON_SETTLERS_LEFT_PX = 41;
			MINIMAP_BUTTON_BUILDINGS_TOP_PX = MINIMAP_LEFT_DECORATION_HEIGHT_PX - 72;
			MINIMAP_BUTTON_BUILDINGS_LEFT_PX = 25;

			PANEL_WIDTH_PX = 216;
			PANEL_HEIGHT_PX = 544;

			float PRIMARY_BUTTON_IMAGE_SIZE_PX_LARGE = 55;
			PRIMARY_TABS_BUTTON_PLACEHOLDER_WIDTH_PX = PRIMARY_BUTTON_IMAGE_SIZE_PX_LARGE - 2; // Button image needs cropping 2 pixels to fit properly
			PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX = 55;
			PRIMARY_TABS_INTER_BUTTON_SPACING_PX = 17;
			PRIMARY_TABS_TOP_PX = PANEL_HEIGHT_PX - 9;
			PRIMARY_TABS_LEFT_PX = 10;

			SECONDARY_TABS_BUTTON_WIDTH_PX = 45;
			SECONDARY_TABS_BUTTON_HEIGHT_PX = 40;
			SECONDARY_TABS_INTER_BUTTON_SPACING_PX = 4;
			SECONDARY_TABS_TOP_PX = PRIMARY_TABS_TOP_PX - PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX;
			SECONDARY_TABS_LEFT_PX = PRIMARY_TABS_LEFT_PX;

			CONTENT_PANE_WIDTH_PX = 197;
			CONTENT_PANE_HEIGHT_PX = 360;
			CONTENT_PANE_TOP_PX = PANEL_HEIGHT_PX - 116;
			CONTENT_PANE_LEFT_PX = 10;

			SYSTEM_BUTTON_PLACEHOLDER_WIDTH_PX = 30;
			SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX = 45;
			SYSTEM_BUTTON_TOP_PX = 8 + SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX;
			SYSTEM_BUTTON_LEFT_PX = PRIMARY_TABS_LEFT_PX;

			LOWER_TABS_BUTTON_WIDTH_PX = 40;
			LOWER_TABS_BUTTON_HEIGHT_PX = 40;
			LOWER_TABS_TOP_PX = 13 + LOWER_TABS_BUTTON_HEIGHT_PX;
			LOWER_TABS_LEFT_PX = 45;

			UI_CENTER_X = (float) 132 / 209;
			UI_DECORATIONRIGHT = (float) 8 / 209 + UI_CENTER_X;
			UI_MINIMAP_DECORATORRIGHT = 0.97f;

			imageSequenceNumber = 2;
		}

		MINIMAP_WIDTH = 124f / 201f;
		MINIMAP_HEIGHT = 135f / 142f;
		MINIMAP_BOTTOMLEFT_X = 3f / 201f;
		MINIMAP_BOTTOM_Y = 5f / 142f;

		MINIMAP_BUTTON_HEIGHT = MINIMAP_BUTTON_HEIGHT_PX / MINIMAP_LEFT_DECORATION_HEIGHT_PX;
		MINIMAP_BUTTON_WIDTH = MINIMAP_BUTTON_WIDTH_PX / MINIMAP_LEFT_DECORATION_WIDTH_PX;

		MINIMAP_BUTTON_ABC_TOP = MINIMAP_BUTTON_ABC_TOP_PX / MINIMAP_LEFT_DECORATION_HEIGHT_PX;
		MINIMAP_BUTTON_ABC_LEFT = MINIMAP_BUTTON_ABC_LEFT_PX / MINIMAP_LEFT_DECORATION_WIDTH_PX;

		MINIMAP_BUTTON_SCROLL_TOP = MINIMAP_BUTTON_SCROLL_TOP_PX / MINIMAP_LEFT_DECORATION_HEIGHT_PX;
		MINIMAP_BUTTON_SCROLL_LEFT = MINIMAP_BUTTON_SCROLL_LEFT_PX / MINIMAP_LEFT_DECORATION_WIDTH_PX;

		MINIMAP_BUTTON_SETTLERS_TOP = MINIMAP_BUTTON_SETTLERS_TOP_PX / MINIMAP_LEFT_DECORATION_HEIGHT_PX;
		MINIMAP_BUTTON_SETTLERS_LEFT = MINIMAP_BUTTON_SETTLERS_LEFT_PX / MINIMAP_LEFT_DECORATION_WIDTH_PX;

		MINIMAP_BUTTON_BUILDINGS_TOP = MINIMAP_BUTTON_BUILDINGS_TOP_PX / MINIMAP_LEFT_DECORATION_HEIGHT_PX;
		MINIMAP_BUTTON_BUILDINGS_LEFT = MINIMAP_BUTTON_BUILDINGS_LEFT_PX / MINIMAP_LEFT_DECORATION_WIDTH_PX;

		UI_TABS1_TOP = PRIMARY_TABS_TOP_PX / PANEL_HEIGHT_PX;
		UI_TABS1_BOTTOM = (PRIMARY_TABS_TOP_PX - PRIMARY_TABS_BUTTON_PLACEHOLDER_HEIGHT_PX) / PANEL_HEIGHT_PX;
		UI_TABS1_SIDEMARGIN = PRIMARY_TABS_LEFT_PX / PANEL_WIDTH_PX;
		UI_TABS1_WIDTH = PRIMARY_TABS_BUTTON_PLACEHOLDER_WIDTH_PX / PANEL_WIDTH_PX;
		UI_TABS1_SPACING = PRIMARY_TABS_INTER_BUTTON_SPACING_PX / PANEL_WIDTH_PX;

		UI_TABS2_TOP = SECONDARY_TABS_TOP_PX / PANEL_HEIGHT_PX;
		UI_TABS2_BOTTOM = (SECONDARY_TABS_TOP_PX - SECONDARY_TABS_BUTTON_HEIGHT_PX) / PANEL_HEIGHT_PX;
		UI_TABS2_SIDEMARGIN = SECONDARY_TABS_LEFT_PX / PANEL_WIDTH_PX;
		UI_TABS2_WIDTH = SECONDARY_TABS_BUTTON_WIDTH_PX / PANEL_WIDTH_PX;
		UI_TABS2_SPACING = SECONDARY_TABS_INTER_BUTTON_SPACING_PX / PANEL_WIDTH_PX;

		CONTENT_TOP = CONTENT_PANE_TOP_PX / PANEL_HEIGHT_PX;
		CONTENT_BOTTOM = (CONTENT_PANE_TOP_PX - CONTENT_PANE_HEIGHT_PX) / PANEL_HEIGHT_PX;
		CONTENT_LEFT = CONTENT_PANE_LEFT_PX / PANEL_WIDTH_PX;
		CONTENT_RIGHT = (CONTENT_PANE_LEFT_PX + CONTENT_PANE_WIDTH_PX) / PANEL_WIDTH_PX;

		SYSTEM_BUTTON_TOP = SYSTEM_BUTTON_TOP_PX / PANEL_HEIGHT_PX;
		SYSTEM_BUTTON_BOTTOM = (SYSTEM_BUTTON_TOP_PX - SYSTEM_BUTTON_PLACEHOLDER_HEIGHT_PX) / PANEL_HEIGHT_PX;
		SYSTEM_BUTTON_LEFT = SYSTEM_BUTTON_LEFT_PX / PANEL_WIDTH_PX;
		SYSTEM_BUTTON_RIGHT = (SYSTEM_BUTTON_LEFT_PX + SYSTEM_BUTTON_PLACEHOLDER_WIDTH_PX) / PANEL_WIDTH_PX;

		LOWER_TABS_TOP = LOWER_TABS_TOP_PX / PANEL_HEIGHT_PX;
		LOWER_TABS_BOTTOM = (LOWER_TABS_TOP_PX - LOWER_TABS_BUTTON_HEIGHT_PX) / PANEL_HEIGHT_PX;
		LOWER_TABS_LEFT = LOWER_TABS_LEFT_PX / PANEL_WIDTH_PX;
		LOWER_TABS_WIDTH = LOWER_TABS_BUTTON_WIDTH_PX / PANEL_WIDTH_PX;

		// file
		final int UI_BG_FILE = 4;

		// sequences
		final int UI_BG_SEQINDEX_MAIN = 2;
		final int UI_BG_SEQINDEX_MINIMAPR = 1;
		final int UI_BG_SEQINDEX_MINIMAPL = 0;
		final int UI_BG_SEQINDEX_RIGHT = 3;

		UI_BG_SEQ_MAIN = new OriginalImageLink(EImageLinkType.SETTLER, UI_BG_FILE, UI_BG_SEQINDEX_MAIN, imageSequenceNumber);
		UI_BG_SEQ_MINIMAPR = new OriginalImageLink(EImageLinkType.SETTLER, UI_BG_FILE, UI_BG_SEQINDEX_MINIMAPR, imageSequenceNumber);
		UI_BG_SEQ_MINIMAPL = new OriginalImageLink(EImageLinkType.SETTLER, UI_BG_FILE, UI_BG_SEQINDEX_MINIMAPL, imageSequenceNumber);
		UI_BG_SEQ_RIGHT = new OriginalImageLink(EImageLinkType.SETTLER, UI_BG_FILE, UI_BG_SEQINDEX_RIGHT, imageSequenceNumber);
	}
}