//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 06:39:01 PM CET 
//

package jsettlers.mapcreator.presetloader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import jsettlers.common.material.EMaterialType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dx" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class Object {

	@XmlAttribute(name = "dx")
	protected Integer dx;
	@XmlAttribute(name = "dy")
	protected Integer dy;
	@XmlAttribute(name = "type")
	protected EMaterialType type;
	@XmlAttribute(name = "count")
	protected Integer count;

	/**
	 * Gets the value of the dx property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getDx() {
		return dx;
	}

	/**
	 * Sets the value of the dx property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setDx(Integer value) {
		this.dx = value;
	}

	/**
	 * Gets the value of the dy property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getDy() {
		return dy;
	}

	/**
	 * Sets the value of the dy property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setDy(Integer value) {
		this.dy = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return EMaterialType
	 * 
	 */
	public EMaterialType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            EMaterialType
	 * 
	 */
	public void setType(EMaterialType value) {
		this.type = value;
	}

	/**
	 * Gets the value of the count property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * Sets the value of the count property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCount(Integer value) {
		this.count = value;
	}

}
